name: Build docker images
on: [push]

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: [2.7, 3.5, 3.6, 3.7, 3.8]
        poetry-version: ["latest", "preview"]
        os: ["alpine"]
    steps:
    - uses: actions/checkout@v1
    - name: Build and publish
      uses: mr-smithers-excellent/docker-build-push@v1.0
      with:
        registry: docker.io
        username: nicklehmann
        password: ${{ secrets.DOCKER_PASSWORD }}

        image: nicklehmann/poetry
        tag: py${{ matrix.python-version }}-${{ matrix.poetry-version }}-${{ matrix.os }}

        dockerfile: ${{ matrix.python-version }}/${{ matrix.os }}/${{ matrix.poetry-version }}/Dockerfile
