name: Build docker images
on: [push]

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: 
          - "3.5"
          - "3.6"
          - "3.7"
          - "3.8"
          - "3.9"
          - "3.10"
        poetry-version: ["latest", "preview"]
        os: ["alpine"]
    steps:
      - uses: actions/checkout@v1

      - name: Login to DockerHub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - name: Build and push
        uses: docker/build-push-action@v3
        with:
          push: true
          tags: blockloop/poetry:${{ matrix.python-version }}-${{ matrix.poetry-version }}-${{ matrix.os }}
          file: ${{ matrix.python-version }}/${{ matrix.os }}/${{ matrix.poetry-version }}/Dockerfile

  update_description:
    name: Update description
    runs-on: ubuntu-latest
    steps:
      - name: Docker Hub Description
        uses: peter-evans/dockerhub-description@v2.1.0
        env:
          DOCKERHUB_USERNAME: ${{ secrets.DOCKERHUB_USERNAME }}
          DOCKERHUB_PASSWORD: ${{ secrets.DOCKERHUB_TOKEN }}
          DOCKERHUB_REPOSITORY: blockloop/poetry
