name: Build docker images
on: [push]

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version:
          - "3.9"
          - "3.10"
        poetry-version: ["latest", "preview"]
        os: ["alpine"]
    steps:
      - uses: actions/checkout@v1

      - name: Login to DockerHub
        uses: docker/login-action@v2
        with:
          username: blockloop
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - name: Build and push
        uses: docker/build-push-action@v3
        with:
          push: true
          tags: blockloop/poetry:${{ matrix.python-version }}-${{ matrix.poetry-version }}-${{ matrix.os }}
          file: ${{ matrix.python-version }}/${{ matrix.os }}/${{ matrix.poetry-version }}/Dockerfile

  update_description:
    name: Update docker hub description
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1

      - name: Docker Hub README & description sync
        uses: meeDamian/sync-readme@v1.0.6
        with:
          user: blockloop
          pass: ${{ secrets.DOCKERHUB_TOKEN }}
          slug: blockloop/poetry
